#!/usr/bin/env python3
"""
Clean Test File - Remove AI-generated comments and keep only test cases.

This script removes:
- Enhancement headers and metadata
- Inline correction comments
- AI-generated section markers
- Any other comments added by the test enhancer

Keeps:
- Original category comments (e.g., # basic: Basic test cases)
- Test case lines
- Include statements
"""

import sys
import re
from pathlib import Path
from typing import List


def clean_test_file(input_file: Path, output_file: Path = None, in_place: bool = False) -> None:
    """
    Clean a test file by removing AI-generated comments.
    
    Args:
        input_file: Path to the test file to clean
        output_file: Path to save cleaned file (if not in_place)
        in_place: If True, modify the file in place
    """
    if not input_file.exists():
        print(f"Error: File not found: {input_file}")
        sys.exit(1)
    
    with open(input_file, 'r') as f:
        lines = f.readlines()
    
    cleaned_lines = []
    skip_until_marker = False
    last_was_test_case = False
    
    for line in lines:
        stripped = line.strip()
        
        # Skip enhancement header blocks
        if '============================================================================' in stripped:
            skip_until_marker = True
            continue
        
        # Skip until we find the ai_generated marker or a test case
        if skip_until_marker:
            if stripped.startswith('# ai_generated:') or (stripped and not stripped.startswith('#')):
                skip_until_marker = False
                if stripped.startswith('# ai_generated:'):
                    continue
            else:
                continue
        
        # Skip specific AI-generated metadata patterns
        if any(pattern in stripped for pattern in [
            'ENHANCED TEST CASES',
            'Generated by Claude',
            'Generated:',
            'Corrections Applied:',
            'Tests Added:',
            'CORRECTIONS APPLIED:',
            'End of AI-generated tests',
            '# ai_generated:'
        ]):
            continue
        
        # Remove inline correction comments
        if '# CORRECTED:' in line:
            # Keep the test case but remove the comment
            line = line.split('# CORRECTED:')[0].rstrip() + '\n'
        
        # Keep the line if it's not empty or is a meaningful comment
        if stripped:
            # Keep SUBSTRAIT directives (###)
            if stripped.startswith('###'):
                cleaned_lines.append(line)
                last_was_test_case = False
            # Keep category comments (format: # category_name: Description)
            elif stripped.startswith('#') and ':' in stripped:
                # Add blank line before category comment if previous line was a test case
                if last_was_test_case and cleaned_lines and cleaned_lines[-1].strip():
                    cleaned_lines.append('\n')
                cleaned_lines.append(line)
                last_was_test_case = False
            # Keep include statements
            elif stripped.startswith('include '):
                cleaned_lines.append(line)
                last_was_test_case = False
            # Keep test case lines (contain = and parentheses)
            elif '=' in stripped and '(' in stripped:
                cleaned_lines.append(line)
                last_was_test_case = True
            # Keep other non-comment lines
            elif not stripped.startswith('#'):
                cleaned_lines.append(line)
                last_was_test_case = False
    
    # Remove excessive blank lines (more than 2 consecutive)
    final_lines = []
    blank_count = 0
    for line in cleaned_lines:
        if line.strip():
            final_lines.append(line)
            blank_count = 0
        else:
            blank_count += 1
            if blank_count <= 2:
                final_lines.append(line)
    
    # Write output
    if in_place:
        output_path = input_file
    elif output_file:
        output_path = output_file
    else:
        # Default: add .cleaned suffix
        output_path = input_file.parent / f"{input_file.stem}.cleaned{input_file.suffix}"
    
    with open(output_path, 'w') as f:
        f.writelines(final_lines)
    
    print(f"✓ Cleaned file saved to: {output_path}")
    print(f"  Original lines: {len(lines)}")
    print(f"  Cleaned lines: {len(final_lines)}")
    print(f"  Removed: {len(lines) - len(final_lines)} lines")


def clean_directory(input_dir: Path, output_dir: Path = None, recursive: bool = False) -> None:
    """
    Clean all test files in a directory.
    
    Args:
        input_dir: Directory containing test files
        output_dir: Directory to save cleaned files
        recursive: If True, process subdirectories
    """
    if not input_dir.exists():
        print(f"Error: Directory not found: {input_dir}")
        sys.exit(1)
    
    # Find all .test files
    pattern = "**/*.test" if recursive else "*.test"
    test_files = list(input_dir.glob(pattern))
    
    if not test_files:
        print(f"No test files found in {input_dir}")
        return
    
    print(f"Found {len(test_files)} test file(s) to clean\n")
    
    for test_file in test_files:
        # Determine output path
        if output_dir:
            # Preserve directory structure
            rel_path = test_file.relative_to(input_dir)
            output_file = output_dir / rel_path
            output_file.parent.mkdir(parents=True, exist_ok=True)
        else:
            output_file = None
        
        print(f"Cleaning {test_file.name}...")
        clean_test_file(test_file, output_file)
        print()


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Clean test files by removing AI-generated comments",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Clean a single file (creates .cleaned version)
  python scripts/clean_test_file.py test-suites-enhanced/functions/arithmetic/add.test
  
  # Clean in place
  python scripts/clean_test_file.py test-suites-enhanced/functions/arithmetic/add.test --in-place
  
  # Clean with specific output file
  python scripts/clean_test_file.py input.test --output cleaned.test
  
  # Clean entire directory
  python scripts/clean_test_file.py test-suites-enhanced/functions/arithmetic --output test-suites-clean/arithmetic
  
  # Clean directory recursively
  python scripts/clean_test_file.py test-suites-enhanced/functions --output test-suites-clean --recursive
        """
    )
    
    parser.add_argument(
        "input",
        help="Input test file or directory"
    )
    parser.add_argument(
        "--output",
        help="Output file or directory (default: adds .cleaned suffix)"
    )
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="Modify file(s) in place (WARNING: overwrites original)"
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Process directories recursively"
    )
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    output_path = Path(args.output) if args.output else None
    
    if input_path.is_file():
        clean_test_file(input_path, output_path, args.in_place)
    elif input_path.is_dir():
        if args.in_place:
            print("WARNING: --in-place will overwrite original files!")
            response = input("Continue? (yes/no): ")
            if response.lower() != 'yes':
                print("Cancelled.")
                sys.exit(0)
        clean_directory(input_path, output_path, args.recursive)
    else:
        print(f"Error: Not a file or directory: {input_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()

