#!/usr/bin/env python3
"""
Process test files to prepare for open source release:
1. Remove AI-generated comment banners
2. Reorganize AI-generated tests into semantic groups
3. Maintain all test lines (no deletions)
4. Track metadata for documentation
"""

import os
import re
from pathlib import Path
from typing import List, Dict, Tuple
import json

# Base directory for test files
TEST_BASE_DIR = Path("test-suites/functions")

# Metadata tracking
metadata = {
    "processed_files": [],
    "total_files": 0,
    "total_tests_reorganized": 0,
    "categories": {}
}


def categorize_test_line(line: str, function_name: str) -> str:
    """Categorize a test line based on its content."""
    line_lower = line.lower()
    
    # Check for overflow behavior first (specific pattern)
    if 'overflow' in line_lower or 'saturate' in line_lower or 'silent' in line_lower:
        return "overflow_behavior"
    
    # Check for special floating point values
    if any(val in line_lower for val in ['nan', 'inf', '-inf', 'infinity']):
        return "special_values"
    
    # Check for boundary/edge cases (max/min values)
    if any(val in line for val in ['2147483647', '-2147483648', '9223372036854775807', 
                                     '-9223372036854775808', '127', '-128', '32767', 
                                     '-32768', '255', '65535', '4294967295']):
        return "edge_cases"
    
    # Check for null handling
    if 'null' in line_lower and ('=' in line or 'null_handling' in line_lower):
        return "null_handling_extended"
    
    # Check for zero values
    if re.search(r'\b0+\b', line) or '0.0' in line or '-0.0' in line:
        return "zero_handling"
    
    # Check for precision/small values
    if 'e-' in line_lower or any(val in line for val in ['1e-308', '1e-100', '0.1', '0.333']):
        return "precision"
    
    # Check for unicode/special characters
    if any(char in line for char in ['🎉', '🎊', '🎈', '🔥', '🌟', '世界', '한국', '日本', 
                                       '中国', 'café', 'naïve', 'Ω', 'α', 'β']):
        return "unicode_handling"
    
    # Check for empty strings/values
    if "''" in line or '""' in line or '()::' in line:
        return "empty_values"
    
    # Check for single value tests
    if re.search(r'\(\d+\)::', line) or re.search(r'\([^,)]+\)::', line):
        return "single_value"
    
    # Check for large datasets
    if line.count(',') > 15:
        return "large_datasets"
    
    # Check for mixed magnitude
    if 'e10' in line_lower or 'e-10' in line_lower or '1000000' in line:
        return "mixed_magnitude"
    
    # Check for negative numbers (not already categorized)
    if re.search(r'-\d+', line) and 'edge_cases' not in line:
        return "negative_values"
    
    # Check for type coverage
    if any(t in line for t in ['::i8', '::i16', '::i32', '::i64', '::u8', '::u16', 
                                 '::u32', '::u64', '::fp32', '::fp64']):
        return "type_coverage"
    
    # Check for whitespace handling
    if r'\t' in line or r'\n' in line or '  ' in line:
        return "whitespace_handling"
    
    # Default category
    return "additional_coverage"


def extract_function_name(filepath: Path) -> str:
    """Extract function name from file path."""
    return filepath.stem


def process_test_file(filepath: Path) -> Dict:
    """Process a single test file."""
    print(f"Processing: {filepath}")
    
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    # Find the AI-generated section
    ai_banner_start = -1
    ai_banner_end = -1
    ai_section_start = -1
    ai_section_end = -1
    
    for i, line in enumerate(lines):
        if '# ============================================================================' in line:
            if ai_banner_start == -1 and i + 1 < len(lines):
                # Check if next line contains AI marker
                if 'ENHANCED TEST CASES' in lines[i + 1] or 'Generated by Claude' in lines[i + 1]:
                    ai_banner_start = i
            elif ai_banner_start != -1 and ai_banner_end == -1:
                # This is the closing banner line
                ai_banner_end = i
        elif '# ai_generated:' in line:
            ai_section_start = i
        elif '# End of AI-generated tests' in line:
            ai_section_end = i
            break
    
    # Validate we found all markers
    if ai_section_start == -1 or ai_section_end == -1:
        return {
            "filepath": str(filepath),
            "status": "no_ai_section",
            "tests_reorganized": 0
        }
    
    # Extract sections
    header_section = lines[:ai_banner_start] if ai_banner_start != -1 else lines[:ai_section_start]
    ai_tests = lines[ai_section_start + 1:ai_section_end]
    
    # Remove empty lines and comment-only lines from ai_tests
    ai_tests = [line for line in ai_tests if line.strip() and not line.strip().startswith('#')]
    
    if not ai_tests:
        return {
            "filepath": str(filepath),
            "status": "no_tests_found",
            "tests_reorganized": 0
        }
    
    # Categorize AI tests
    function_name = extract_function_name(filepath)
    categorized_tests = {}
    
    for test_line in ai_tests:
        category = categorize_test_line(test_line, function_name)
        if category not in categorized_tests:
            categorized_tests[category] = []
        categorized_tests[category].append(test_line)
    
    # Build new file content
    new_lines = header_section.copy()
    
    # Add reorganized AI tests with proper headers
    if categorized_tests:
        new_lines.append('\n')
        new_lines.append('# ============================================================================\n')
        new_lines.append('# ENHANCED TEST CASES\n')
        new_lines.append('# Additional test cases for comprehensive coverage\n')
        new_lines.append('# ============================================================================\n')
        new_lines.append('\n')
        
        # Define category order and descriptions
        category_order = [
            ("edge_cases", "Boundary values and extreme inputs"),
            ("overflow_behavior", "Overflow and saturation behavior"),
            ("special_values", "Special floating point values (NaN, Infinity)"),
            ("null_handling_extended", "Extended null handling scenarios"),
            ("zero_handling", "Zero and negative zero handling"),
            ("precision", "Floating point precision and small values"),
            ("single_value", "Single value inputs"),
            ("empty_values", "Empty strings and collections"),
            ("negative_values", "Negative number handling"),
            ("type_coverage", "Various data type coverage"),
            ("unicode_handling", "Unicode and special characters"),
            ("whitespace_handling", "Whitespace and control characters"),
            ("mixed_magnitude", "Mixed magnitude values"),
            ("large_datasets", "Large input datasets"),
            ("additional_coverage", "Additional test coverage")
        ]
        
        for category, description in category_order:
            if category in categorized_tests:
                new_lines.append(f'# {category}: {description}\n')
                for test_line in categorized_tests[category]:
                    new_lines.append(test_line)
                new_lines.append('\n')
    
    # Write back to file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    
    return {
        "filepath": str(filepath),
        "status": "processed",
        "tests_reorganized": len(ai_tests),
        "categories": list(categorized_tests.keys())
    }


def process_all_test_files():
    """Process all test files in the test-suites/functions directory."""
    test_files = list(TEST_BASE_DIR.rglob("*.test"))
    metadata["total_files"] = len(test_files)
    
    print(f"Found {len(test_files)} test files to process\n")
    
    for test_file in sorted(test_files):
        result = process_test_file(test_file)
        metadata["processed_files"].append(result)
        
        if result["status"] == "processed":
            metadata["total_tests_reorganized"] += result["tests_reorganized"]
            
            # Track categories
            category = str(test_file.parent.name)
            if category not in metadata["categories"]:
                metadata["categories"][category] = {
                    "files": 0,
                    "tests": 0
                }
            metadata["categories"][category]["files"] += 1
            metadata["categories"][category]["tests"] += result["tests_reorganized"]
    
    # Save metadata
    metadata_file = TEST_BASE_DIR / "enhancement_metadata.json"
    with open(metadata_file, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)
    
    print(f"\n{'='*80}")
    print(f"Processing complete!")
    print(f"Total files processed: {metadata['total_files']}")
    print(f"Total tests reorganized: {metadata['total_tests_reorganized']}")
    print(f"Metadata saved to: {metadata_file}")
    print(f"{'='*80}\n")


if __name__ == "__main__":
    process_all_test_files()

# Made with Bob
